import { Subject, LyceeFiliere } from "./types";

export const CEM_SUBJECTS: Subject[] = [
  { name: "Arabe", coef: 3 },
  { name: "Français", coef: 3 },
  { name: "Mathématiques", coef: 3 },
  { name: "Sciences naturelles", coef: 2 },
  { name: "Physique/Chimie", coef: 2 },
  { name: "Histoire/Géo", coef: 2 },
  { name: "Éducation islamique", coef: 1 },
  { name: "Éducation civique", coef: 1 },
  { name: "Anglais", coef: 1 },
  { name: "Éducation physique", coef: 1 },
];

export const MOYEN_SUBJECTS: Subject[] = [
  { name: "Arabe", coef: 3 },
  { name: "Français", coef: 2 },
  { name: "Mathématiques", coef: 3 },
  { name: "Sciences naturelles", coef: 2 },
  { name: "Physique/Chimie", coef: 2 },
  { name: "Histoire/Géo", coef: 2 },
  { name: "Anglais", coef: 1 },
  { name: "Éd. islamique", coef: 1 },
  { name: "Éd. civique", coef: 1 },
  { name: "Éd. physique", coef: 1 },
];

export const LYCEE_SUBJECTS: Record<LyceeFiliere, Subject[]> = {
  science: [
    { name: "Arabe", coef: 2 },
    { name: "Français", coef: 2 },
    { name: "Mathématiques", coef: 6 },
    { name: "Sciences naturelles", coef: 6 },
    { name: "Physique/Chimie", coef: 6 },
    { name: "Histoire/Géo", coef: 1 },
    { name: "Anglais", coef: 2 },
    { name: "Philo", coef: 1 },
    { name: "Éd. islamique", coef: 1 },
    { name: "Éd. physique", coef: 1 },
  ],
  math: [
    { name: "Arabe", coef: 2 },
    { name: "Français", coef: 2 },
    { name: "Mathématiques", coef: 9 },
    { name: "Physique/Chimie", coef: 7 },
    { name: "Sciences naturelles", coef: 2 },
    { name: "Histoire/Géo", coef: 1 },
    { name: "Anglais", coef: 2 },
    { name: "Philo", coef: 1 },
    { name: "Éd. islamique", coef: 1 },
    { name: "Éd. physique", coef: 1 },
  ],
  technique: [
    { name: "Arabe", coef: 2 },
    { name: "Français", coef: 2 },
    { name: "Mathématiques", coef: 6 },
    { name: "Physique/Chimie", coef: 5 },
    { name: "Technique mathématique", coef: 6 },
    { name: "Histoire/Géo", coef: 1 },
    { name: "Anglais", coef: 2 },
    { name: "Philo", coef: 1 },
    { name: "Éd. islamique", coef: 1 },
    { name: "Éd. physique", coef: 1 },
  ],
  lettres: [
    { name: "Arabe", coef: 5 },
    { name: "Français", coef: 4 },
    { name: "Anglais", coef: 4 },
    { name: "Philo", coef: 4 },
    { name: "Histoire/Géo", coef: 4 },
    { name: "Éd. islamique", coef: 2 },
    { name: "Mathématiques", coef: 1 },
    { name: "Sciences naturelles", coef: 1 },
    { name: "Éd. physique", coef: 1 },
  ],
  gestion: [
    { name: "Arabe", coef: 2 },
    { name: "Français", coef: 3 },
    { name: "Anglais", coef: 3 },
    { name: "Mathématiques", coef: 4 },
    { name: "Gestion/Compta", coef: 6 },
    { name: "Économie", coef: 4 },
    { name: "Histoire/Géo", coef: 2 },
    { name: "Philo", coef: 1 },
    { name: "Éd. islamique", coef: 1 },
    { name: "Éd. physique", coef: 1 },
  ],
};